### ISSUE TITLE
Is it good to add 60 mins break when signed out?

### ISSUE THREAD

**Issue by halsk** [Georepublic/miyamoto#21]
It is annoying I have to record break time.
Is it good to add 60 mins break automatically when the working time exceeds 5 hours?

**Comment by iosefa** [comment]
I thought it might be okay also to have a bot reminder when work time exceeds 5 hours. Something like: 

"Wow! You've been at it for 5 hours straight! Time to go for a walk, have a coffee or tea, and have a break!" 

There can even be a dialog (not sure how simple this is): 

"Shall I schedule a 60-minute break starting now?"
