### ISSUE TITLE
Multiple records in one day

### ISSUE THREAD

**Issue by halsk** [Georepublic/miyamoto#24]
Mentioned by iosefa.

> hmm… is there a way to start and stop the timer multiple times during a day? It seems that you can only start the timer once and then stop it once for the day. I will often work for a few hours, then take a break, then work for more hours … I sometimes cannot accurately anticipate how long my breaks will be. I.e. a pause feature would be nice

**Comment by iosefa** [comment]
@halsk you beat me to it! But I will close this issue and keep #25 open since it is a little more descriptive of what I was thinking. thanks!

**Comment by iosefa** [comment]
@halsk I cannot close issues that I did not create.
