### ISSUE TITLE
Hide daily 11:50 JST Miyamoto-san's notices

### ISSUE THREAD

**Issue by sanak** [Georepublic/miyamoto#29]
Currently, the following Miyamoto-san's notices are posted at 11:50 JST everyday, but it may be good to hide such maintenance notices.

```
最新のみやもとさんの準備ができました！
https://github.com/masuidrive/miyamoto/blob/master/UPDATE.md を読んでください。
```

```
# 私の成長記録
## 20141027.0
- アップデートメッセージが消えない問題が直りました。ごめんなさい。
## 20141022.0
- アップデートチェックが直りました。
- アップデート内容をお伝えします！
## 20141021.0
- 日付がよく分からなくなっていたのですが、ちゃんと勉強しました。
## 20141019.0
- migrateを修正
- 一般公開
## 20141016.1
- テストの為にバージョンアップ
## 20141016.0
− テスト公開
```

**Comment by sanak** [comment]
@halsk 
I think that following operation may be necessary, but I couldn't select `ファイル` / `版の管理`  menu because of lack of permission.
https://github.com/masuidrive/miyamoto/blob/master/UPDATE.md
![file_menu](https://user-images.githubusercontent.com/629923/77750286-d7ef9800-7066-11ea-8345-72eab12d7b10.png)

**Comment by halsk** [comment]
I think this is fixec.
